import { TradeEvent, TemperReport, CoachFactsPayload } from './types';

export const mockTradeEvents: TradeEvent[] = [
  {
    id: 't1',
    index: 0,
    timestamp: '2026-05-15T09:30:05.000Z',
    symbol: 'SPY',
    side: 'BUY',
    qty: 100,
    price: 412.50,
    realizedPnl: 0,
    runningPnl: 0,
    label: 'BOOK',
    symbolCode: '📖',
    reasons: ['Opening Range Breakout', 'Volume Surge'],
  },
  {
    id: 't2',
    index: 1,
    timestamp: '2026-05-15T09:32:10.000Z',
    symbol: 'SPY',
    side: 'SELL',
    qty: 100,
    price: 413.20,
    realizedPnl: 70,
    runningPnl: 70,
    label: 'GOOD',
    symbolCode: '!',
    reasons: ['Target Hit'],
  },
  {
    id: 't3',
    index: 2,
    timestamp: '2026-05-15T09:35:45.000Z',
    symbol: 'QQQ',
    side: 'BUY',
    qty: 50,
    price: 320.00,
    realizedPnl: 0,
    runningPnl: 70,
    label: 'MISTAKE',
    symbolCode: '?',
    reasons: ['Chasing', 'Extended per VWAP'],
  },
  {
    id: 't4',
    index: 3,
    timestamp: '2026-05-15T09:40:00.000Z',
    symbol: 'QQQ',
    side: 'SELL',
    qty: 50,
    price: 318.50,
    realizedPnl: -75,
    runningPnl: -5,
    label: 'BLUNDER',
    symbolCode: '??',
    reasons: ['Panic Sell', 'Oversized Loss'],
  },
  {
    id: 't5',
    index: 4,
    timestamp: '2026-05-15T09:42:00.000Z',
    symbol: 'QQQ',
    side: 'BUY',
    qty: 100, // Doubling down
    price: 319.00,
    realizedPnl: 0,
    runningPnl: -5,
    label: 'INACCURACY',
    symbolCode: '?!',
    reasons: ['Revenge Trading', 'Size Up on Tilt'],
  },
  {
    id: 't6',
    index: 5,
    timestamp: '2026-05-15T09:45:00.000Z',
    symbol: 'QQQ',
    side: 'SELL',
    qty: 100,
    price: 321.00,
    realizedPnl: 200,
    runningPnl: 195,
    label: 'BRILLIANT', // Lucky/Brilliant outcome though process was sketchy? Or actually brilliant recovery? let's create a good one.
    symbolCode: '!!',
    reasons: ['Perfect Exit', 'Disciplined Hold'], 
  }
];

export const mockTemperReport: TemperReport = {
  id: 'session-123',
  date: '2026-05-15',
  temperScore: 72,
  decisionEloBefore: 1250,
  decisionEloAfter: 1265,
  trades: mockTradeEvents,
  biases: [
    { type: 'REVENGE_TRADING', score: 65 },
    { type: 'FOMO', score: 40 },
  ],
  disciplinedReplay: {
    actualPnl: 195,
    disciplinedPnl: 250,
    savedPnl: 55,
    rulesViolated: 2,
  },
  summary: {
    totalTrades: 6,
    winRate: 0.66,
    grossPnl: 195,
    maxDrawdown: -80,
    dominantBias: 'Revenge Trading',
  },
};

export const mockCoachFacts: CoachFactsPayload = {
  overview: {
    date: '2026-05-15',
    temperScore: 72,
    eloBefore: 1250,
    eloAfter: 1265,
    totalTrades: 6,
    grossPnl: 195,
    maxDrawdown: -80,
  },
  biases: [
    { type: 'REVENGE_TRADING', score: 65 },
  ],
  labelSummary: [
    { label: 'BRILLIANT', count: 1, percentage: 16.6 },
    { label: 'GOOD', count: 1, percentage: 16.6 },
    { label: 'BOOK', count: 1, percentage: 16.6 },
    { label: 'MISTAKE', count: 1, percentage: 16.6 },
    { label: 'BLUNDER', count: 1, percentage: 16.6 },
    { label: 'INACCURACY', count: 1, percentage: 16.6 },
  ],
  keyEvents: [
    {
      tradeId: 't4',
      index: 3,
      timestamp: '2026-05-15T09:40:00.000Z',
      label: 'BLUNDER',
      symbolCode: '??',
      reasons: ['Panic Sell'],
      pnl: -75,
    },
    {
      tradeId: 't6',
      index: 5,
      timestamp: '2026-05-15T09:45:00.000Z',
      label: 'BRILLIANT',
      symbolCode: '!!',
      reasons: ['Perfect Exit'],
      pnl: 200,
    },
  ],
  tiltSequences: [
    {
      id: 'tilt-1',
      startIndex: 2,
      endIndex: 4,
      durationMinutes: 7,
      dominantBias: 'Revenge Trading',
    },
  ],
  disciplinedReplay: {
    actualPnl: 195,
    disciplinedPnl: 250,
    savedPnl: 55,
  },
  coachText: {
    intro: "A mixed session. You started well with a book trade, but let a loss spiral into revenge trading before recovering beautifully.",
    strengths: [
      "Excellent recognition of the opening range breakout.",
      "managed to close the session green despite mid-game tilt.",
    ],
    weaknesses: [
      "Heavy revenge trading tendency after the first loss.",
      "Doubling down on a losing position is a major leak.",
    ],
    suggestions: [
      "Implement a hard stop rule: walk away for 5 mins after any loss > 1R.",
      "Review your 'adding to losers' criteria.",
    ],
  },
};
